### ISSUE TITLE
provide a watch method that watches a single entity (giving the namespace and name)

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes-api#1]
not sure if the underlying watch stuff supports this yet - there's the label + filter options on the websocket stuff AFAIK.

Worst case, we could write a little facade for now to do the filtering of the objects for the name you give - until we can do it a bit more efficiently

**Comment by jimmidyson** [comment]
The way to do this is via a `fieldSelector` on the entity list.
