### ISSUE TITLE
K8S Service Account

### ISSUE THREAD

**Issue by ninckblokje** [hawtio/hawtio-kubernetes-api#11]
Hi,

Is is possible to use this library with a service account in Kubernetes?

Jeroen

**Comment by astefanutti** [comment]
This module depends on https://github.com/hawtio/hawtio-oauth for the authentication and basically calls `HawtioOAuth.getOAuthToken()` to retrieve the token passed in the `Authorization` header of each request. I haven't tested it, though it should be possible to provide a service account token, with a few tweaks to the hawtio-oauth lib.
